version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.2.1
  node: circleci/node@5

jobs:
  use-gcp:
    executor: gcp-cli/default
    steps:
      - run:
          name: Saving the OIDC token to the oidc token file  path
          command: |
            mkdir -p /home/circleci/creds
      - gcp-cli/setup:
          version: latest
          use_oidc: true
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test --passWithNoTests
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - gcp-cli/setup:
          version: latest
          use_oidc: true
      - run:
          name: Set up Docker for gcloud
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
      - run:
          name: Docker build
          command: |
            docker build -t react-app .
      - run:
          name: Tag Docker image
          command: |
            docker tag react-app us-central1-docker.pkg.dev/elite-totality-418717/react-portfolio/portfolio-image
      - run:
          name: Push docker image
          command: | 
            docker push us-central1-docker.pkg.dev/elite-totality-418717/react-portfolio/portfolio-image
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-cli/setup:
          version: latest
          use_oidc: true
      - run:
          name: Update the container image for the instance
          command: |
            gcloud compute instances update-container virtual-machine --project=elite-totality-418717 --zone us-west4-b  --container-image=us-central1-docker.pkg.dev/elite-totality-418717/react-portfolio/portfolio-image:latest
  

workflows:
  main:
    jobs: 
      - use-gcp
      - test-node
      - build:
          requires:
            - use-gcp
          filters:
             branches:
               only:
                 - main
      - release-approval:
          type: approval
          requires:
            - test-node
            - build
            - use-gcp
          filters:
             branches:
               only:
                 - main
      - deploy:
          requires:
            - test-node
            - build
            - release-approval
            - use-gcp
          filters:
             branches:
               only:
                 - main 