version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.2.1
parameters:
  google_project_number: 
    type: string
    default: $GOOGLE_PROJECT_NUMBER
  workload_identity_pool_id: 
    type: string
    default: $GCP_WIP_ID
  workload_identity_pool_provider_id: 
    type: string
    default: $GCP_WIP_PROVIDER_ID
  service_account_email: 
    type: string
    default: $GCP_SERVICE_ACCOUNT_EMAIL
  gcp_cred_config_file_path: 
    type: string
    default: /home/circleci/creds/gcp_cred_config.json
jobs:
  use-gcp:
    executor: gcp-cli/default
    steps:
      - run:
          name: Saving the OIDC token to the oidc token file  path
          command: |
            mkdir -p /home/circleci/creds
      - gcp-cli/setup:
          version: latest
          use_oidc: true
      - run:
          name: Creating an  instance
          command: gcloud compute instances create instance --zone=us-west4-b

workflows:
  build-test-deploy:
    jobs:
      - use-gcp