version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.2.1

commands:
  gcp-oidc-generate-cred-config-file:
    description: "Authenticate with GCP using a CircleCI OIDC token."
    parameters:
      project_id:
        type: string
        default: elite-totality-418717
      workload_identity_pool_id:
        type: string
        default: cicd
      workload_identity_pool_provider_id:
        type: string
        default: circleci
      service_account_email:
        type: string
        default: wifmanager@elite-totality-418717.iam.gserviceaccount.com
      gcp_cred_config_file_path:
        type: string
        default: /home/circleci/gcp_cred_config.json
      oidc_token_file_path:
        type: env_var_name
        default: CIRCLE_OIDC_TOKEN_FILE
    steps:
      - run:
          command: |
            # Store OIDC token in temp file
            echo $CIRCLE_OIDC_TOKEN > << parameters.oidc_token_file_path >>
            # Create a credential configuration for the generated OIDC ID Token
            gcloud iam workload-identity-pools create-cred-config \
                projects/elite-totality-418717/locations/global/workloadIdentityPools/cicd/providers/circleci-provider\
                --output-file=/home/circleci/gcp_cred_config.json \
                --service-account=wifmanager@elite-totality-418717.iam.gserviceaccount.com \
                --credential-source-file=/home/circleci/oidc_token.json
      - run:
          command: |
                ls /home
      - run:
          command: |
                ls /home/circleci/
      - run:
          command: |
                cat /home/circleci/oidc_token.json
      - run:
          command: |
                cat /home/circleci/gcp_cred_config.json

  gcp-oidc-authenticate:
    description: "Authenticate with GCP using a GCP credentials file."
    parameters:
      gcp_cred_config_file_path:
        type: string
        default: /home/circleci/gcp_cred_config.json
    steps:
      - run:
          command: |
            # Configure gcloud to leverage the generated credential configuration
            gcloud auth login --brief --cred-file=/home/circleci/gcp_cred_config.json
            # Configure ADC
            echo "export GOOGLE_APPLICATION_CREDENTIALS='<< parameters.gcp_cred_config_file_path >>'" | tee -a "$BASH_ENV"
jobs:
  gcp-oidc-defaults:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
      - gcp-oidc-generate-cred-config-file
      - gcp-oidc-authenticate
      - run:
          name: Verify that gcloud is authenticated
          environment:
            GCP_SERVICE_ACCOUNT_EMAIL: wifmanager@elite-totality-418717.iam.gserviceaccount.com
          command: gcloud iam service-accounts get-iam-policy wifmanager@elite-totality-418717.iam.gserviceaccount.com

workflows:
  main:
    jobs:
      - gcp-oidc-defaults:
          name: Generate Creds File and Authenticate
          context:
          - myContext
