version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.2.1
jobs:
  use-gcp:
    executor: gcp-cli/default
    steps:
      - run:
          name: Saving the OIDC token to the oidc token file  path
          command: |
            mkdir -p /home/circleci/creds
      - gcp-cli/setup:
          version: latest
          use_oidc: true
          service_account_email: $OIDC_SERVICE_ACCOUNT_EMAIL
          gcp_cred_config_file_path: home/circleci/creds/gcp_cred_config.json
          workload_identity_pool_id: $OIDC_WIP_ID   
          workload_identity_pool_provider_id: $OIDC_WIP_PROVIDER_ID
          google_project_number: $GOOGLE_PROJECT_NUMBER

workflows:
  build-test-deploy:
    jobs:
      - use-gcp